// flow-typed signature: 9ab573dc756a7a03548a1bbdfcfc789b
// flow-typed version: <<STUB>>/closest_v0.0.1/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'closest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'closest' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'closest/index' {
  declare module.exports: $Exports<'closest'>;
}
declare module 'closest/index.js' {
  declare module.exports: $Exports<'closest'>;
}
