// flow-typed signature: 53c8fe11149c83d7bdcd4d8eb4c867e9
// flow-typed version: <<STUB>>/gulp-develop-server_v^0.4.3/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-develop-server'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-develop-server' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'gulp-develop-server/index' {
  declare module.exports: $Exports<'gulp-develop-server'>;
}
declare module 'gulp-develop-server/index.js' {
  declare module.exports: $Exports<'gulp-develop-server'>;
}
