// flow-typed signature: ae944349df44958dcb6452281c29a1ad
// flow-typed version: <<STUB>>/gulp-handlebars_v^4.0.0/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-handlebars'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-handlebars' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'gulp-handlebars/index' {
  declare module.exports: $Exports<'gulp-handlebars'>;
}
declare module 'gulp-handlebars/index.js' {
  declare module.exports: $Exports<'gulp-handlebars'>;
}
