// flow-typed signature: 1b4666d5ad9cdc5241abe35a3922f55f
// flow-typed version: <<STUB>>/gulp-define-module_v^0.1.3/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-define-module'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-define-module' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gulp-define-module/coverage/prettify' {
  declare module.exports: any;
}

declare module 'gulp-define-module/coverage/sorter' {
  declare module.exports: any;
}

declare module 'gulp-define-module/test/expected/basic_amd_named' {
  declare module.exports: any;
}

declare module 'gulp-define-module/test/expected/basic_amd_require' {
  declare module.exports: any;
}

declare module 'gulp-define-module/test/expected/basic_amd' {
  declare module.exports: any;
}

declare module 'gulp-define-module/test/expected/basic_commonjs_require' {
  declare module.exports: any;
}

declare module 'gulp-define-module/test/expected/basic_commonjs' {
  declare module.exports: any;
}

declare module 'gulp-define-module/test/expected/basic_es6_require' {
  declare module.exports: any;
}

declare module 'gulp-define-module/test/expected/basic_es6' {
  declare module.exports: any;
}

declare module 'gulp-define-module/test/expected/basic_hybrid_require' {
  declare module.exports: any;
}

declare module 'gulp-define-module/test/expected/basic_hybrid' {
  declare module.exports: any;
}

declare module 'gulp-define-module/test/expected/basic_node_require' {
  declare module.exports: any;
}

declare module 'gulp-define-module/test/expected/basic_node' {
  declare module.exports: any;
}

declare module 'gulp-define-module/test/expected/basic_plain_context_file' {
  declare module.exports: any;
}

declare module 'gulp-define-module/test/expected/basic_plain_context_name' {
  declare module.exports: any;
}

declare module 'gulp-define-module/test/expected/basic_plain_wrapped' {
  declare module.exports: any;
}

declare module 'gulp-define-module/test/expected/basic_plain' {
  declare module.exports: any;
}

declare module 'gulp-define-module/test/fixtures/basic' {
  declare module.exports: any;
}

declare module 'gulp-define-module/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gulp-define-module/coverage/prettify.js' {
  declare module.exports: $Exports<'gulp-define-module/coverage/prettify'>;
}
declare module 'gulp-define-module/coverage/sorter.js' {
  declare module.exports: $Exports<'gulp-define-module/coverage/sorter'>;
}
declare module 'gulp-define-module/index' {
  declare module.exports: $Exports<'gulp-define-module'>;
}
declare module 'gulp-define-module/index.js' {
  declare module.exports: $Exports<'gulp-define-module'>;
}
declare module 'gulp-define-module/test/expected/basic_amd_named.js' {
  declare module.exports: $Exports<'gulp-define-module/test/expected/basic_amd_named'>;
}
declare module 'gulp-define-module/test/expected/basic_amd_require.js' {
  declare module.exports: $Exports<'gulp-define-module/test/expected/basic_amd_require'>;
}
declare module 'gulp-define-module/test/expected/basic_amd.js' {
  declare module.exports: $Exports<'gulp-define-module/test/expected/basic_amd'>;
}
declare module 'gulp-define-module/test/expected/basic_commonjs_require.js' {
  declare module.exports: $Exports<'gulp-define-module/test/expected/basic_commonjs_require'>;
}
declare module 'gulp-define-module/test/expected/basic_commonjs.js' {
  declare module.exports: $Exports<'gulp-define-module/test/expected/basic_commonjs'>;
}
declare module 'gulp-define-module/test/expected/basic_es6_require.js' {
  declare module.exports: $Exports<'gulp-define-module/test/expected/basic_es6_require'>;
}
declare module 'gulp-define-module/test/expected/basic_es6.js' {
  declare module.exports: $Exports<'gulp-define-module/test/expected/basic_es6'>;
}
declare module 'gulp-define-module/test/expected/basic_hybrid_require.js' {
  declare module.exports: $Exports<'gulp-define-module/test/expected/basic_hybrid_require'>;
}
declare module 'gulp-define-module/test/expected/basic_hybrid.js' {
  declare module.exports: $Exports<'gulp-define-module/test/expected/basic_hybrid'>;
}
declare module 'gulp-define-module/test/expected/basic_node_require.js' {
  declare module.exports: $Exports<'gulp-define-module/test/expected/basic_node_require'>;
}
declare module 'gulp-define-module/test/expected/basic_node.js' {
  declare module.exports: $Exports<'gulp-define-module/test/expected/basic_node'>;
}
declare module 'gulp-define-module/test/expected/basic_plain_context_file.js' {
  declare module.exports: $Exports<'gulp-define-module/test/expected/basic_plain_context_file'>;
}
declare module 'gulp-define-module/test/expected/basic_plain_context_name.js' {
  declare module.exports: $Exports<'gulp-define-module/test/expected/basic_plain_context_name'>;
}
declare module 'gulp-define-module/test/expected/basic_plain_wrapped.js' {
  declare module.exports: $Exports<'gulp-define-module/test/expected/basic_plain_wrapped'>;
}
declare module 'gulp-define-module/test/expected/basic_plain.js' {
  declare module.exports: $Exports<'gulp-define-module/test/expected/basic_plain'>;
}
declare module 'gulp-define-module/test/fixtures/basic.js' {
  declare module.exports: $Exports<'gulp-define-module/test/fixtures/basic'>;
}
declare module 'gulp-define-module/test/test.js' {
  declare module.exports: $Exports<'gulp-define-module/test/test'>;
}
