// flow-typed signature: b7b036c07639e29bb607bf3ca68acba8
// flow-typed version: <<STUB>>/hbsfy_v^2.2.1/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'hbsfy'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'hbsfy' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'hbsfy/example/index-bundle' {
  declare module.exports: any;
}

declare module 'hbsfy/example/index' {
  declare module.exports: any;
}

declare module 'hbsfy/runtime' {
  declare module.exports: any;
}

declare module 'hbsfy/test/bom_test' {
  declare module.exports: any;
}

declare module 'hbsfy/test/browsercode' {
  declare module.exports: any;
}

declare module 'hbsfy/test/browserify_test' {
  declare module.exports: any;
}

declare module 'hbsfy/test/custom_compiler_subargs_test' {
  declare module.exports: any;
}

declare module 'hbsfy/test/custom_extension_subargs_test' {
  declare module.exports: any;
}

declare module 'hbsfy/test/custom_extension_test' {
  declare module.exports: any;
}

declare module 'hbsfy/test/custom_precompiler_options_test' {
  declare module.exports: any;
}

declare module 'hbsfy/test/custom_precompiler_subargs_test' {
  declare module.exports: any;
}

declare module 'hbsfy/test/error_test' {
  declare module.exports: any;
}

declare module 'hbsfy/test/indentation_test' {
  declare module.exports: any;
}

declare module 'hbsfy/test/inline_partial_require_test' {
  declare module.exports: any;
}

declare module 'hbsfy/test/inlinePartialBrowsercode' {
  declare module.exports: any;
}

declare module 'hbsfy/test/partial_require_test' {
  declare module.exports: any;
}

declare module 'hbsfy/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'hbsfy/example/index-bundle.js' {
  declare module.exports: $Exports<'hbsfy/example/index-bundle'>;
}
declare module 'hbsfy/example/index.js' {
  declare module.exports: $Exports<'hbsfy/example/index'>;
}
declare module 'hbsfy/index' {
  declare module.exports: $Exports<'hbsfy'>;
}
declare module 'hbsfy/index.js' {
  declare module.exports: $Exports<'hbsfy'>;
}
declare module 'hbsfy/runtime.js' {
  declare module.exports: $Exports<'hbsfy/runtime'>;
}
declare module 'hbsfy/test/bom_test.js' {
  declare module.exports: $Exports<'hbsfy/test/bom_test'>;
}
declare module 'hbsfy/test/browsercode.js' {
  declare module.exports: $Exports<'hbsfy/test/browsercode'>;
}
declare module 'hbsfy/test/browserify_test.js' {
  declare module.exports: $Exports<'hbsfy/test/browserify_test'>;
}
declare module 'hbsfy/test/custom_compiler_subargs_test.js' {
  declare module.exports: $Exports<'hbsfy/test/custom_compiler_subargs_test'>;
}
declare module 'hbsfy/test/custom_extension_subargs_test.js' {
  declare module.exports: $Exports<'hbsfy/test/custom_extension_subargs_test'>;
}
declare module 'hbsfy/test/custom_extension_test.js' {
  declare module.exports: $Exports<'hbsfy/test/custom_extension_test'>;
}
declare module 'hbsfy/test/custom_precompiler_options_test.js' {
  declare module.exports: $Exports<'hbsfy/test/custom_precompiler_options_test'>;
}
declare module 'hbsfy/test/custom_precompiler_subargs_test.js' {
  declare module.exports: $Exports<'hbsfy/test/custom_precompiler_subargs_test'>;
}
declare module 'hbsfy/test/error_test.js' {
  declare module.exports: $Exports<'hbsfy/test/error_test'>;
}
declare module 'hbsfy/test/indentation_test.js' {
  declare module.exports: $Exports<'hbsfy/test/indentation_test'>;
}
declare module 'hbsfy/test/inline_partial_require_test.js' {
  declare module.exports: $Exports<'hbsfy/test/inline_partial_require_test'>;
}
declare module 'hbsfy/test/inlinePartialBrowsercode.js' {
  declare module.exports: $Exports<'hbsfy/test/inlinePartialBrowsercode'>;
}
declare module 'hbsfy/test/partial_require_test.js' {
  declare module.exports: $Exports<'hbsfy/test/partial_require_test'>;
}
declare module 'hbsfy/test/test.js' {
  declare module.exports: $Exports<'hbsfy/test/test'>;
}
