// flow-typed signature: 5be1c6210ef452cf1852c627d7ad2d58
// flow-typed version: <<STUB>>/hbsify_v^1.0.1/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'hbsify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'hbsify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'hbsify/Gruntfile' {
  declare module.exports: any;
}

declare module 'hbsify/test/mocha/test-compile' {
  declare module.exports: any;
}

// Filename aliases
declare module 'hbsify/Gruntfile.js' {
  declare module.exports: $Exports<'hbsify/Gruntfile'>;
}
declare module 'hbsify/index' {
  declare module.exports: $Exports<'hbsify'>;
}
declare module 'hbsify/index.js' {
  declare module.exports: $Exports<'hbsify'>;
}
declare module 'hbsify/test/mocha/test-compile.js' {
  declare module.exports: $Exports<'hbsify/test/mocha/test-compile'>;
}
