// flow-typed signature: 32e848dc10714f00a78881b9540ea1d0
// flow-typed version: <<STUB>>/markov_v0.0.7/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'markov'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'markov' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'markov/example/qwantz' {
  declare module.exports: any;
}

declare module 'markov/test/cycles' {
  declare module.exports: any;
}

declare module 'markov/test/has' {
  declare module.exports: any;
}

declare module 'markov/test/limit' {
  declare module.exports: any;
}

declare module 'markov/test/order' {
  declare module.exports: any;
}

declare module 'markov/test/stream' {
  declare module.exports: any;
}

// Filename aliases
declare module 'markov/example/qwantz.js' {
  declare module.exports: $Exports<'markov/example/qwantz'>;
}
declare module 'markov/index' {
  declare module.exports: $Exports<'markov'>;
}
declare module 'markov/index.js' {
  declare module.exports: $Exports<'markov'>;
}
declare module 'markov/test/cycles.js' {
  declare module.exports: $Exports<'markov/test/cycles'>;
}
declare module 'markov/test/has.js' {
  declare module.exports: $Exports<'markov/test/has'>;
}
declare module 'markov/test/limit.js' {
  declare module.exports: $Exports<'markov/test/limit'>;
}
declare module 'markov/test/order.js' {
  declare module.exports: $Exports<'markov/test/order'>;
}
declare module 'markov/test/stream.js' {
  declare module.exports: $Exports<'markov/test/stream'>;
}
