// flow-typed signature: 5d3c0493642264845a1c9e21f33e2d5d
// flow-typed version: <<STUB>>/simple-transition_v^1.0.0/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'simple-transition'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'simple-transition' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'simple-transition/index' {
  declare module.exports: $Exports<'simple-transition'>;
}
declare module 'simple-transition/index.js' {
  declare module.exports: $Exports<'simple-transition'>;
}
