// flow-typed signature: e40cb10eaad376824665227bddffa646
// flow-typed version: <<STUB>>/throttle_v^1.0.3/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'throttle'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'throttle' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'throttle/example/stdio' {
  declare module.exports: any;
}

declare module 'throttle/test/throttle' {
  declare module.exports: any;
}

declare module 'throttle/throttle' {
  declare module.exports: any;
}

// Filename aliases
declare module 'throttle/example/stdio.js' {
  declare module.exports: $Exports<'throttle/example/stdio'>;
}
declare module 'throttle/test/throttle.js' {
  declare module.exports: $Exports<'throttle/test/throttle'>;
}
declare module 'throttle/throttle.js' {
  declare module.exports: $Exports<'throttle/throttle'>;
}
